description: >
  This is a sample executor using Docker and Node. If you want to provide a custom environment in your orb, insert your image here.
  If you do not require an executor, you can simply delete this directory.
docker:
  - image: 'liquibase/liquibase:<<parameters.tag>>'
parameters:
  tag:
    default: latest
    description: >
      Pick a specific liquibase/liquibase image variant:
      https://hub.docker.com/r/liquibase/liquibase/tags
    type: string
